### ISSUE TITLE
Feat Request: concurrency support

### ISSUE THREAD

**Issue by tiamed** [echowaves/expo-cached-image#4] opened 2022-04-08 02:53 UTC
Support downloading multiple images at the same time

**Comment by dmitryame** [comment] 2022-04-08 14:26
Not sure I understand the request. I'm using the CachedImage tag in [FlatList](https://facebook.github.io/react-native/docs/flatlist.html) and it seems to be working perfectly fine with multiple images.

**Comment by dmitryame** [comment] 2022-04-08 14:27
Or you mean enhancing addToCache method in CacheManager to be able to populate multiple cache entries concurrently?

**Comment by tiamed** [comment] 2022-04-09 16:48
> Or you mean enhancing addToCache method in CacheManager to be able to populate multiple cache entries concurrently?

Not sure if it's the cache or network part, what I observe is when loading uncached images, it loads one by one instead of loading multiple images at the same time

**Comment by tiamed** [comment] 2022-04-10 11:54
On iOS the images from web are loaded concurrently, but on Android 12 it's not

**Comment by dmitryame** [comment] 2022-04-11 01:16
What you are describing seems like an OS issue. Not sure it would be possible to address in the library.

**Comment by tiamed** [comment] 2022-06-23 10:43
Seems like it's related to the downloading behavior in this lib, using Image component from React Native does support loading multiple images concurrently on Android.

**Comment by dmitryame** [comment] 2022-07-27 16:11
I'm unable to reproduce the issue. Will be closing for how, let me know if you have more specific info for share, can re-open it then.

**Closed by dmitryame** 2022-07-27 16:11 UTC
