### ISSUE TITLE
Resetting Cache on URI Change

### ISSUE THREAD

**Issue by stevewirig** [echowaves/expo-cached-image#1] opened 2021-09-01 20:18 UTC
I am not sure if this is a bug or working as intended, but when I use the cacheKey that cache seems to be persisting and ignoring if the URI associated with the cache changes.  Is there a way to force the cache reset?  

For example, if I update a URI of a cached image and the cacheKey remains the same.  I would expect the cache to update to the new image.

**Comment by dmitryame** [comment] 2021-09-02 15:24
Will close it for now, since it works as designed. Let me know if you were able to make it work for your use-case. We can think about potential solutions if needed.

**Closed by dmitryame** 2021-09-02 15:24 UTC

**Comment by vbylen** [comment] 2022-08-01 05:57
Where would one find the `CONST.PENDING_UPLOADS_FOLDER` variable?

**Comment by dmitryame** [comment] 2022-08-01 13:50
That's just one of the application specific constants. I define it in my app like this:
```
export const PENDING_UPLOADS_FOLDER = `${FileSystem.documentDirectory}pendingUploads/`
```
Basically, in the example above, I take a file from upload folder which is going to be submitted to the server and stick it into the cache proactively, so that when this image is requested on this device to be shown, it will not have to make one more round trip to the server.

**Comment by vbylen** [comment] 2022-08-15 23:59
I'm getting the following error

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/57633368/184755325-bff696cf-4800-46de-85f8-585ad40c53bd.png">

Here's the code

```jsx
  const picker = useImagePicker({
    onSuccess: async (images) => {
      setLoading(true)
      if (images[0]?.base64) {
        const base64Result = await uploadToPhotoroom(images[0]?.base64)
        if (!base64Result) return setError('Upload failed - we are so sorry')
        const image = await uploadToSupabase(base64Result)
        if (!image) return setError('Upload failed. Are you logged in?')
        await CacheManager.addToCache({
          file: `${FileSystem.documentDirectory}pendingUploads/${image}`,
          key: getCacheKey(image),
        })
        await updateProfile({ avatarUrl: image })
        setImageUrl(image)
        setLoading(false)
      } else {
        setLoading(false)
        setError('The image you uploaded could not be processed')
      }
    },
  })

I would like to re-render the image when the cachekey changes. 

You've mentioned this isn't implemented in the library for performance reasons.

Changing the profile picture is a common enough use case though I think where that is really needed. 

How would you recommend going forward in this case?

```

**Comment by dmitryame** [comment] 2022-08-16 01:29
Look at the output, the value of `${FileSystem.documentDirectory}pendingUploads/${image}` seems to be pointing to a file which can't be referenced -- you can't be making `http://10.0.` etc... part of the legitimate file name on the local file system. If you are trying to reference a different external image which referenced by a different key, there is nothing special you need to do, just use <CachedImage> tag with the new key, and it will perform the magic of downloading it from the remote source and sticking it in the local cache for future use. If you already have the file on the local system and want to avoid downloading it again, make sure you are referencing the local file by the correct URI in the `addToCache` method.
For further troubleshooting, start with console.log the value of the file parameter and the value of the key.

```
console.log({
          file: `${FileSystem.documentDirectory}pendingUploads/${image}`,
          key: getCacheKey(image),
})
```
